### ISSUE TITLE
Windows: CRLF newlines in cookie file causes error "net/http: invalid byte '\r' in Cookie.Value"

### ISSUE THREAD

**Issue by laurence-myers** [Magnitus-/gogcli#18]
```cmd
E:\Apps\Net\gogcli>gogcli update generate
2022/06/26 11:29:50 net/http: invalid byte '\r' in Cookie.Value; dropping invalid bytes
2022/06/26 11:29:51 net/http: invalid byte '\r' in Cookie.Value; dropping invalid bytes
2022/06/26 11:29:51 net/http: invalid byte '\r' in Cookie.Value; dropping invalid bytes
2022/06/26 11:29:51 net/http: invalid byte '\r' in Cookie.Value; dropping invalid bytes
2022/06/26 11:29:51 net/http: invalid byte '\r' in Cookie.Value; dropping invalid bytes
2022/06/26 11:29:53 net/http: invalid byte '\r' in Cookie.Value; dropping invalid bytes
^C
```

Probably just need to add instructions to the README to save the cookie file using LF line endings. (Could be tricky for non-technical users)

**Comment by Magnitus-** [comment]
There is probably a way to strip/ignore it. I'll validate a fix on my windows machine after I've validated everything else for the next release.

**Comment by Magnitus-** [comment]
I validated that the problem occurred with a previous version of gogcli, but did not occur with version 0.20.0 that was just released, so I think the fix did the trick.

I'll close this ticket, but feel free to reopen it if you find the problem persist with version 0.20.0 or later.
