### ISSUE TITLE
Not sure if related to this or the GUI created for it but it appeared to be missing some files.

### ISSUE THREAD

**Issue by TomTurbine** [Magnitus-/gogcli#26]
I used this with GOGcli-GUI
https://github.com/Twombs/GOGcli-GUI

Not sure which was the cause, but I noticed with Fallout 4, it refused to pull up all the installer files, I think it was missing part 2 of the multiple parts, didn't matter how many times I refreshed, it still seemed to miss it.

**Comment by Magnitus-** [comment]
> I used this with GOGcli-GUI https://github.com/Twombs/GOGcli-GUI
> 
> Not sure which was the cause, but I noticed with Fallout 4, it refused to pull up all the installer files, I think it was missing part 2 of the multiple parts, didn't matter how many times I refreshed, it still seemed to miss it.

I have the game downloaded so gogcli is probably ok with it, but I'll double-check anyways this weekend.

**Comment by Magnitus-** [comment]
Actually, I just took a quick look now.

I generated a manifest and all the files where listed. I then applied the manifest to a local file storage and all the files where also listed in the action list.

I didn't download the files (the game is pretty large), but at this point, I validated gogcli quite a bit with my game collection (which is rather large) and can say with confidence that if a game file is present in the actions to add/update, one of two things will happen:
- It will get downloaded
- If the download fails repeatedly, the command to execute actions will exist in failure and you'll be able to resume exactly where it failed at a later point in time.

**Comment by TomTurbine** [comment]
Sorry, meant to update this. It actually corrected itself at a later date. No clue what the issue was or why, but a day or two later it started showing all the files just fine.

**Comment by Magnitus-** [comment]
Ok, I'll close this issue. If possible when you experience issues in the future, try to use gogcli directly in the terminal to see if it is the source of the problem or not.

In my case, I typed the following commands:
```
gogcli manifest generate --title="Fallout 4"
# Looked at manifest file and determined all game files were in it
gogcli storage apply manifest -k fs
# Looked at actions file and determined all game files were present as actions to add
```

On windows, the file would be "gogcli.exe".
